# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-23 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appts',
            name='date',
            field=models.DateField(verbose_name='%Y,%m,%d'),
        ),
        migrations.AlterField(
            model_name='appts',
            name='time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
