# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appts', '0005_auto_20180224_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appts',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
