# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appts', '0006_auto_20180224_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='appts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appts', to='appts.Users'),
        ),
    ]
