# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appts', '0007_appts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appts',
            name='date',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
    ]
